plugins { id 'com.android.application' }

android {
    namespace 'com.jlxc.vehicledatacore'
    compileSdk 34

    defaultConfig {
        applicationId 'com.jlxc.vehicledatacore'
        minSdk 23
        targetSdk 28
        versionCode 2
        versionName '0.1.1-buildfix'
    }

    buildFeatures {
        aidl true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
